version: "3.0"
services:
  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./src/main/resources/:/docker-entrypoint-initdb.d" # init script
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: customerdb
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
